language: php

php:
  - 5.6
  - 7.0
  - hhvm
  
sudo: false

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer install --prefer-source --no-interaction --dev

script:
  - if [ "$TRAVIS_PHP_VERSION" != "5.6" ]; then ./vendor/bin/phpunit; fi
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then ./vendor/bin/phpunit --coverage-text --coverage-clover coverage.xml; fi

after_success:
  - bash <(curl -s https://codecov.io/bash)
